---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: all_except_apache2
    run_list:
      - recipe[apt]
      - recipe[yum]
      - recipe[zabbix-custom-checks::apt-update-check]
      - recipe[zabbix-custom-checks::chef-client]
      - recipe[zabbix-custom-checks::mongodb]
      - recipe[zabbix-custom-checks::nginx]
      - recipe[zabbix-custom-checks::openvz-virtual]
      - recipe[zabbix-custom-checks::redis]
      - recipe[zabbix-custom-checks::varnish]
    attributes:
  - name: apache2
    run_list:
      - recipe[apt]
      - recipe[yum]
      - recipe[zabbix-custom-checks::apache2]
    attributes:
